name: Run all unit test

on:
  push:
    branches: [main]
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [16.x]  # Update to a version that satisfies pnpm requirements

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies and run tests
        run: |
          pnpm --filter web install
          pnpm --filter web test:unit
